---
# For a full list of vmware_guest parameters, visit:
# http://docs.ansible.com/ansible/latest/vmware_guest_module.html

# vcenter parameters
hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
username: "{{ lookup('env', 'VMWARE_USER') }}"
password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
validate_certs: false
template:
datacenter:
cluster:
folder: "/vm/Discovered virtual machine"

# vm guest parameters
vm_names:
memory_mb: 1024
num_cpus: 1
notes: Provisioned via Ansible
state: poweredon
wait_for_ip_address: true

## vm networking parameters
vm_networks:
  - name: "{{ network_0_vlan | default('VM Network') }}"
    ### ip assignment (dhcp or static)
    type: "{{ network_0_type | default('dhcp') }}"
    ### device_type - (e1000, e1000e, pcnet32, vmxnet2, vmxnet3)
    device_type: "{{ network_0_device_type | default('vmxnet3') }}"

    ### static network parameters
    # ip: "{{ network_0_ip | default(omit, true) }}"
    # netmask: "{{ network_0_netmask | default(omit, true) }}"
    # gateway: "{{ network_0_gateway | default(omit, true) }}"
    # mac: "{{ network_0_mac | default(omit, true) }}"
    # domain: "{{ network_0_dnsdomain | default(omit, true) }}"
    # dns_servers:
    #   - "{{ network_0_dns_0_server | default(omit, true) }}"
    #   - "{{ network_0_dns_1_server | default(omit, true) }}"

## vm disk parameters
# disks:
#   - size_gb: "{{ vm_disk_0_size_gb }}"
#     type: "{{ vm_disk_0_type | default('thin') }}"
#     datastore: "{{ vm_disk_0_datastore }}"
#   - size_gb: "{{ vm_disk_1_size_gb }}"
#     type: "{{ vm_disk_1_type | default('thin') }}"
#     datastore: "{{ vm_disk_1datastore }}"

## vm customization parameters
# customizations:

## vm linked clone parameter
snapshot_src:
linked_clone: false

# asynchronous parameters
async_wait: 3600
async_poll: 0
async_retries: 100

# enable extra debugging
verbose: false
